[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/.netlify/functions/mdm-gallery"
  to = "/.netlify/functions/mdm-gallery"
  status = 200
